name: CI Pipeline

on:
  push:
    branches:
      - main

env:
  DOCKER_IMAGE: zaralx-ru-frontend:latest

jobs:
  build:
    name: Build Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: docker build -t ${{ env.DOCKER_IMAGE }} .

      - name: Save Docker image as tar
        run: docker save ${{ env.DOCKER_IMAGE }} -o image.tar

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: image-tar
          path: image.tar

  deploy:
    name: Deploy to Server 1
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: image-tar

      - name: Install SSH and SSHpass
        run: sudo apt-get update && sudo apt-get install -y sshpass

      - name: Copy Docker image to server
        env:
          SSHPASS: ${{ secrets.SERVER1_PASSWORD }}
        run: sshpass -e scp -v -o StrictHostKeyChecking=no image.tar deployuser@${{ secrets.SERVER1_HOST }}:/var/images/zaralx-ru-frontend.tar

      - name: Load Docker image on server
        env:
          SSHPASS: ${{ secrets.SERVER1_PASSWORD }}
        run: sshpass -e ssh -v -o StrictHostKeyChecking=no deployuser@${{ secrets.SERVER1_HOST }} 'docker load -i /var/images/zaralx-ru-frontend.tar'
